<?php
// app/Components/NewsCard.php

namespace App\Components;

use App\Helpers;

class NewsCard {
    /**
     * Render a standard news article card UI component
     * 
     * @param array $article The news article data from database
     * @param bool $isPriority LCP priority image loading (preloads, no lazy-load)
     */
    public static function render(array $article, bool $isPriority = false): string {
        $categoryLabel = Helpers::getCategoryLabel($article['category']);
        $categoryColor = Helpers::getCategoryColor($article['category']);
        $formattedDate = Helpers::formatDate($article['date_published']);
        $readTime = Helpers::getReadingTime($article['content']);
        
        $articleUrl = 'news/' . $article['id'] . '/' . self::slugify($article['title']);
        $imageHtml = self::renderResponsiveImage($article['image_path'], $article['title'], $isPriority);
        
        return sprintf('
            <article class="news-card" data-category="%s">
                <div class="news-card-image-wrap">
                    %s
                    <span class="category-badge" style="background-color: %s;">%s</span>
                </div>
                <div class="news-card-content">
                    <div class="news-card-meta">
                        <span><i class="far fa-calendar-alt"></i> %s</span>
                        <span><i class="far fa-clock"></i> %s</span>
                    </div>
                    <h3 class="news-card-title">
                        <a href="%s" class="news-card-link">%s</a>
                    </h3>
                    <p class="news-card-excerpt">%s</p>
                    <div class="news-card-footer">
                        <span class="news-card-author">By %s</span>
                        <a href="%s" class="btn-read-more" aria-label="Read full article about %s">Read More <i class="fas fa-arrow-right"></i></a>
                    </div>
                </div>
            </article>
        ',
            htmlspecialchars($article['category']),
            $imageHtml,
            htmlspecialchars($categoryColor),
            htmlspecialchars($categoryLabel),
            htmlspecialchars($formattedDate),
            htmlspecialchars($readTime),
            htmlspecialchars($articleUrl),
            htmlspecialchars($article['title']),
            htmlspecialchars($article['summary']),
            htmlspecialchars($article['author']),
            htmlspecialchars($articleUrl),
            htmlspecialchars($article['title'])
        );
    }

    /**
     * Render picture element with AVIF/WebP srcset fallbacks
     */
    private static function renderResponsiveImage(string $imagePath, string $altText, bool $isPriority = false): string {
        // Fallback for external Unsplash images in default seeder
        if (str_starts_with($imagePath, 'http')) {
            $loadingAttr = $isPriority ? 'fetchpriority="high"' : 'loading="lazy"';
            return sprintf('<img src="%s" alt="%s" class="news-card-img" %s>', htmlspecialchars($imagePath), htmlspecialchars($altText), $loadingAttr);
        }

        $pathInfo = pathinfo($imagePath);
        $dir = $pathInfo['dirname'];
        $base = $pathInfo['filename'];
        
        // Match sizes generated by ImagePipeline
        $widths = [
            'thumbnail' => 300,
            'medium'    => 800,
            'large'     => 1200
        ];
        
        $avifSrcset = [];
        $webpSrcset = [];
        $fallbackSrcset = [];
        
        foreach ($widths as $sizeKey => $w) {
            $avifPath = $dir . '/' . $base . '_' . $sizeKey . '.avif';
            $webpPath = $dir . '/' . $base . '_' . $sizeKey . '.webp';
            $fallbackPath = $dir . '/' . $base . '_' . $sizeKey . '.' . $pathInfo['extension'];
            
            // Check if optimized files exist locally
            if (file_exists(dirname(__DIR__, 2) . '/' . $avifPath)) {
                $avifSrcset[] = $avifPath . ' ' . $w . 'w';
            }
            if (file_exists(dirname(__DIR__, 2) . '/' . $webpPath)) {
                $webpSrcset[] = $webpPath . ' ' . $w . 'w';
            }
            if (file_exists(dirname(__DIR__, 2) . '/' . $fallbackPath)) {
                $fallbackSrcset[] = $fallbackPath . ' ' . $w . 'w';
            }
        }
        
        $loadingAttr = $isPriority ? 'fetchpriority="high"' : 'loading="lazy"';
        $fallbackSrc = $dir . '/' . $base . '_medium.' . $pathInfo['extension'];
        if (!file_exists(dirname(__DIR__, 2) . '/' . $fallbackSrc)) {
            $fallbackSrc = $imagePath;
        }
        
        $html = '<picture class="news-card-picture">';
        
        if (!empty($avifSrcset)) {
            $html .= sprintf('<source type="image/avif" srcset="%s" sizes="(max-width: 768px) 100vw, 33vw">', htmlspecialchars(implode(', ', $avifSrcset)));
        }
        if (!empty($webpSrcset)) {
            $html .= sprintf('<source type="image/webp" srcset="%s" sizes="(max-width: 768px) 100vw, 33vw">', htmlspecialchars(implode(', ', $webpSrcset)));
        }
        if (!empty($fallbackSrcset)) {
            $html .= sprintf('<source srcset="%s" sizes="(max-width: 768px) 100vw, 33vw">', htmlspecialchars(implode(', ', $fallbackSrcset)));
        }
        
        $html .= sprintf('<img src="%s" alt="%s" class="news-card-img" %s>', htmlspecialchars($fallbackSrc), htmlspecialchars($altText), $loadingAttr);
        $html .= '</picture>';
        
        return $html;
    }

    /**
     * Generate URL slug helper
     */
    private static function slugify(string $text): string {
        $text = preg_replace('~[^\pL\d]+~u', '-', $text);
        $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        $text = preg_replace('~[^-\w]+~', '', $text);
        $text = trim($text, '-');
        $text = preg_replace('~-+~', '-', $text);
        $text = strtolower($text);
        return empty($text) ? 'article' : $text;
    }
}
